#Runs all the tests! Triggers on push and PR for quick feedback.
#Tests are not very comprehensive right now, so don't put too much faith in this.
name: run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Install Tools
        run: make prep

      - name: Execute tests
        run: make test && make testacc

      - name: Upload test artifacts for debugging
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
        if: failure()
        with:
          name: test-debug-artifacts
          path: |
            datasource/*/git_*_basic_test.pkr.hcl
            datasource/*/packer_log_git_*_basic_test.txt
          if-no-files-found: ignore
