# This is a manually triggered action workflow.
# It uses Packer at latest version to init, validate and build
# an example configuration in a folder.
# This action is compatible with Packer v1.7.0 or later.
name: test plugin example

on:
  workflow_dispatch:
    inputs:
      logs:
        description: 'Set 1 to activate full logs'
        required: false
        default: '0'

jobs:
  build:
    runs-on: ubuntu-latest
    name: init and build example
    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Build and Install Plugin
        run: make dev

      - name: Init
        uses: hashicorp/packer-github-actions@ecc5516821087666a672c0d280a0084ea6d9aafd
        with:
          working_directory: './example'
          command: init

      - name: Validate
        uses: hashicorp/packer-github-actions@ecc5516821087666a672c0d280a0084ea6d9aafd
        with:
          working_directory: './example'
          command: validate
        env:
          PACKER_LOG: ${{ github.event.inputs.logs }}

      - name: Build
        uses: hashicorp/packer-github-actions@ecc5516821087666a672c0d280a0084ea6d9aafd
        with:
          working_directory: './example'
          command: build
        env:
          PACKER_LOG: ${{ github.event.inputs.logs }}
